#!/bin/bash

aksi_array+=("twit_bacot")

# main method
twit_bacot_main() {

  # bacotan, source:
  # http://lintas-terbaru.blogspot.com/2013/11/kata-kata-lucu-update-status-twitter.html
  # http://www.bloggergubug.com/2013/01/update-status-gokil-anti-galau-2013.html
  # http://munafsiq.blogspot.com/2012/09/status-lucu.html
  bacotan_array=(
      "Beb, Semalem aku ngimpi indaaaaah banget | ngimpi kita nikah ya? | bukan, tp ngimpi kita putus | =,,="
      "Semua LDR itu SETIA - SEring TIdak Apel.... #Eh"
      "Menyalahkan diri sendiri itu ga baik. Daripada nyalahin diri sendiri mendingan nyalahin org lain. #Babijak"
      "Gini nih kalo abis mandi gini,,, cakep gue jadi berlebihan gini... Nasib..."
      "#News Diduga ternoda oleh pacar, seorang pemudi nekat mandi dgn deterjen anti noda."
      "Percuma nyuruh pacar makan, yang kenyang juga bukan lo ┒(ˇ_ˇ)┎"
      "Ga usah sok unyu pake monyong2in bibir gitu dong difoto... Inget Kamu itu bukan tukul ┒(ˇ_ˇ)┎"
      "Cowok yg suka foto di Toilet mall itu Kecentilannya meningkat 90% "
      "Hidup itu jgn dibikin susah, coz dulu org tua kita waktu ngebuat kita itu saat mereka lg seneng2. #bijak"
      "Buat cewek #Horror itu saat dia tau, kalo cowoknya punya poster anggota boyband gede banget dikamarnya."
      "Ummm kamu suka mandi pake formalin yah? Kok nge-Jomblonya awet banget?"
      "Rasa malas bangun pagi selalu bisa dikalahkan oleh rasa mules... "
      "Kalo kamu mau punya pacar yg bisa menjaga kamu & hati kamu... Pacaran aja ama security."
      "Cinta sama org Bodoh itu gpp, tp jgn sampe Dibodoh2in ama org karena Cinta -__-"
      "Beb, kalo kamu ga mau aku pacarin,,, gimana kalo kamu aja yg macarin aku? Adil kan?"
      "Wanita peka pada pikirannya, pria peka pada perasaannya & waria peka terhadap Sirine mobil satpol pp"
      "enak yah pacaran ama Alay. Dia ga mungkin selingkuh, karna bisanya CheL1n6kuH."
      "#SoSweet itu ketika liat mantan lagi galau ditimeline, karena diselingkuhin pacar barunya."
      "Anak muda itu baru bangun langsung update status disosmed, bukan mandi..."
      "tidur Mblo, kali aja bangun2 langsung punya pacar... #Eaaa"
      "Ada 3 alasan orang Insomnia: Jomblo, LDR dan Internet. tapi saya ga yakin sama yg ke 3."
      "Jomblo itu jgn dibully, tapi dipacarin... ckckckckck"
      "#SoSweet itu saat lo liat mantan lo lagi jalan sama pacar barunya dan pacarnya lebih jelek dari lo."
      "Jangan salahkan pacar kamu mutusin kamu, salahkan aja diri kamu sendiri kenapa ga mutusin duluan?"
      "Ucapan 'Selamat pagi' di TL adalah salah 1 cara jomblo mencari perhatian, Waspadalah waspadalah."
      "*KFC* siang mas, brapa orang? | 5 | smoking area atau ga? | Jomblo area ada mbak | ....."
      "orang yg suka nyari perhatian pasti dia bercita-cita jadi pussat Infomarsi. #Eaaa"
      "Kematrean seorang wanita, berbanding lurus dengan tingkat kejelekan Prianya. #EaaGitu"
      "Jadilah mantan yg Elegan, yg ga pernah ngajak balikan tapi sering diajak balikan #Nasehat"
      "Hati2 sama yg ngaku Single, mungkin dia Single Parent... #Krik"
      "Jomblo kalo tidur ngimpinya apaan sih?"
      "Kata cewek 'Semua Lelaki itu brengsek' Nah guys kalo lo brengsek berbanggalah, Brarti lo laki."
      "Jomblo mah gitu, ngeliat maling dikejar aja langsung cemburu...."
      "Cowok yg suka galau itu kecantikannya naik 90% #Analis"
      "Kalo mau cari pasangan yg Ideal, jangan lupa 4B: Banyak Duit, Berusaha, Berdoa dan Bercerminlah...."
      "Lihat langit, itulah Ciptaan Tuhan, Lihat Pemandangan, itulah Karya Tuhan, & lihatlah Cermin, itulah Kutukan Tuhan."
      "Jomblo mah gitu, Ngeliat tukang ojek lagi boncengin penumpangnya aja cemburu #Eh"
      "Anak muda itu bangun tidur langsung nyari HP, ngucapin selamat pagi juga harus disosmed... are u?"
      "Kalo ujan gini, pacar pasti jadi pelukable banget ya mblo?"
      "Kalo dapet pacar itu mudah, Jomblo bakalan punah... lestarikan jomblo..!"
      "Kebiasaan Jomblo kalo baru OL ditwitter pasti nulis 'Met Pagi' atau sejenisnya biar dpt perhatian. #Uhuk"
      "Dalam pacaran Perbedaan Umur itu gak penting, yg penting itu Perbedaan Kelamin.. Inget perbedaaan Kelamin..!!"
      "Hey kmu, iya kmu!! Kalau pacar kamu cuma pengen paha sama dada kamu doang , suruh dia pacaran sama pegawai KFC! (¬_¬')"
      "pacaran itu penuh gombal, gombal itu bohong, bohong itu dosa, dosa masuk neraka, jadi pacaran itu bikin masuk Neraka"
      "Pacaran : ngumpulin duit buat nikah | LDR : ngumpulin kangen buat ketemuan | Jomblo : ngumpulin sabun!(۳˚Д˚)۳"
      "Siswa relijius itu, waktu UN lembar jawabnya kosong, tapi ninggalin tulisan 'semuanya kuserahkan kepada Tuhan'"
      "Setiap kejahatan akan mendapat balasannya. Cinta bukan kejahatan, makanya jangan heran jika cinta kadang ga dibalas.."
      "Orang jomblo itu kreatif banget lho. Contoh mereka sengaja pake hape dual sim card, biar bisa sms-sms sendiri, dibales-bales sendiri :p"
      "Jangan suka ngomongin orang dari belakang, kalo kamu ga mau dikentutin."
      "Lebih baik kejebak macet dijalan, dari pada kejebak kenangan dimasa lalu! :p"
      "Mantan itu investasi jangka panjang, kalo kamu kehabisan stok, pergunakanlah mantan #salahbijak"
      "Jika cowok kamu ngelirik cewe lain bersyukurlah, Kamu msih diberi cowo normal. Daripada dia ngelirik cowok lain.."
      "Sayang, kamu mau gak janji sama aku? | anything for you yank.. | janji ya kalo aku minta putus kamu harus nurut -__-"
      "Tabahkan hatimu ,kuatkan imanmu ,putuskan pacarmu, Berikan padaku~"
      "Hidup itu maju kedepan, bukan mundur kebelakang. Lupakan mantan yang ada dimasa lalu, jadikan ia patokan untuk lebih baik dimasa depan!"
      "Jadi jomblo tu serba salah. Jaga jarak dibilang Sombong. Jaga image dibilang Sok Cool. Jaga komplek dibilang Satpam :|"
      "Ternyata air ludah bisa nyembuhin darah rendah.. coba ludahin muka temen lu yang darah rendah, 2 detik langsung naik darahnya.."
      "Tak ada kata terlambat dalam belajar, ya benar, karena yang terlambat itu biasanya pacar.."
      "gue ini berjiwa penolong, karena itu gue selalu nolongin org2 yang perlu bantuan. Tapi yg cakep aja ┒(ˇ_ˇ)┎"
      "Kalau cewek matre lagi sakit mata, mereka nggak perlu ke dokter. Iya.. cukup dikepret pake duit 100 ribuan pasti langsung sembuh :)"
      "Lowbat adalah salah satu musuh pacaran dunia maya/LDR yang paling nyata.."
      "PHP itu keahlian yang dibawa sejak lahir. buktinya nggak pernah diajarkan disekolah... tapi udah pada pinter-pinter :|"
      "Jika mantan adalah masa lalu. Pacar adalah masa depan. Berarti selingkuhan adalah tantangan.."
      "Sebenci apa pun cowok sama pelajaran biologi, pasti bakal duduk paling depan kalo lagi ngebahas tentang 'reproduksi' -_-!"
      "Katanya Gak mau disamain dengan binatang. Tapi masih aja percaya sama ramalan yang lambangnya binatang.."
      "Jomblo itu sumber dari segala kesepian. Jadi buat dukun yang suka bertapa ditempat sepi, ini bisa dimanfaatkan.."
      "Hanya karena 'pacar itu dihati, bukan di bio' lantas kamu naruh nama selingkuhan kamu dibio.."
      "Enak ya jadi alay, Ga pernah sedih. Bisanya cewdih ;("
      "Pacaran: Tuker-tukeran coklat | LDR: Kirim-kiriman coklat | Jomblo: Tukeran Baygon.."
      "Anak twitter kalo kehujanan berteduhnya bukan diemperan toko. tapi di timeline.. :|"
      "Lebih nyesek lagi kalo pacaran sama cewek yang lebih tua dari kita. Iya gitu, mau ciuman aja dikira mau nyium emaknya :'"
      "Teman baik waktu minjem barang selalu Dikembalikan tp sahabat waktu minjem barang slalu pura2 lupa dikembalikan.."
      "Tuhan jika ia jodohku, dekatkanlah padaku, tp jika ia bukan jodohku, jodohin aku dgn sahabatnya (˘ʃƪ˘)"
      "Walau Lo jelek tapi nyari temen itu harus milih2. Ya harus org yang lebih jelek dari lo. Biar lo keliatan cakep #nasehat"
      "#Horror itu saat lo beli baju Couple di olshop. Begitu kiriman baju sampe ga taunya lo udah putus.."
      "Jgn pernah ngomongin masa depan, kalo masa lalu ama mantan aja masih ga bisa dilupain ┒(ˇ_ˇ)┎"
      "Siapa bilang putus cinta itu sakit hati... Bisa aja kan sakit hati banget ┒(ˇ_ˇ)┎"
      "Punya pacar Cakep itu susah... Susah di jelek-jelekinnya kalo udah putus."
      "cowok sejati itu ngupil pake tangan guru killer!"
      "cowok sejati itu main futsal pake bakyak."
      "Jangan lihat cowok itu dari mobil mewah yang dikendarainya. Lihatlah STNK mobil itu dulu, atas nama dia atau bukan."
      "*lagi nonton tv tetangga* *update status* ngantri tiket di XXI panjang beuudh yah ckck."
      "*lagi makan diwarteg* *update status* At Pizza Hut with my friends."
      "Mau apa datang ksni ? | Mau melamar pak.. | Haha.. Kamu jngan melucu yah.. Kerja apa kamu? | Saya pelawak Pak.."
      "Aa dokter ya? | Kok tau? | Karna Aa udah ngobatin hati neng.. | Masa? Aa kan dokter hewan, Neng.."
      "Bang, kecap sebotol berapa? | 20ribu | Mahal amat, di TV aja lebih murah | Yaudah, ibu belinya di TV aja."
      "Malem Minggu --> Pacaran : Bersandar dibahu pacar | Jomblo : Bersandar dibahu jalan. *Pak Minta Paaak.."
      "Single: dapet sms dari cewek di diemin | jomblo: dapet sms dari cewek di 'save as draft' buat kenang2an 1x seumur idup."
      "KFC, Slamat mlm. mau pesan apa? | Saya mau pesen paket Panas 1 ya | Yakin? gak mau tirai nomor 1? Atau amplop yg ada disaku saya?"
      "Abis beli PS baru, PS yg lama langsung rusak. PS yang pengertian.. *Elus-elus PS lama*"
      "Prajurit:'pak, kita telah dikepung dari berbagai arah!' Komandan:'Bagus! sekarang kita bisa menyerang dari segala arah! MUAHAHA!"
      "Anak alim: #AnakMUDAitu keren kalo ibadahnya kuat | Anak alay: #AnakMUDAitu keren kalo lagi joged2 gak jelas di acara musik."
      "cowok sejati nempelin upil di baju mantan!kenaapaaa!?'"
      "abis putus. galau. mau mabok. tapi dikulkas cuma ada susu kental manis. apa bisa mabok pake susu kental manis?"
      "Bt adalah ketika abis mandi gak ada handuk. keluar pake ape gue?"
      "Satu kebodohan pemain sepak bola adalah selalu mengulangi kesalahan dan kekalahan yang sama pada siaran ulangnya!"
      "cowok: Neng kita nikah yuk! | cewek: gak ah bang, aku kan masih sekolah | cowok: oh.. kirain libur."
      "jatuh dari sepeda - biasa | jatuh dari motor - lumayan sakit | jatuh dari mobil - BEGO berarti!"
      "co: leh kenalan? | ce: bleh bang | co: nmanya siapa? | ce: sheila | co: bgus bgt, nama panjangnya? | ce: sheilangkangan | co: %!$%!@$%"
      "alien 1: lo percaya manusia gak? | alien 2: itu tahayul!!"
      "guru: 3xy + 2y² = a-z. carilah x? | gue: beuh, gampang. itu, ada di antara 3 sama y. pinter kan?"
      "Emang kalo mau PACARAN harus punya PACAR dulu ya? Terus, kalo kita mau SARAPAN harus jadi SARAP dulu, gitu?"
      "Voldemort: Dlu saya mengidap pnyakit bisul dihidung. tpi smenjak kenal dng klinik TongFang, saya jdi ga pnya hidung..!!"
      "Kentut terbaik adalah kentut dihadapan orang yang kita gak suka. (y)"
      "Berharap laptop gue berhubungan intim sama HP gue dan berharap mereka akan mempunyai anak iPad."
      "Orang pintar, minum tolak angin. Orang jenius, ke Klinik Tong Fang!"
      "Kalo cewek bilang, 'semua cowok tuh brengsek!'. Pertanyaannya, Berjenis kelamin apakah Bapa mereka?"
      "#KeselAdalah ketika kita lagi download sesuatu, dan ketika udah sampe ████████████ 99%... gagal download!"
      "Aang: Dulu saya sering masuk angin. Tetapi semenjak kenal dengan klinik Tong Fang, saya jadi pengendali angin. Terimakasih Tong Fang!"
      "gue: mah, ada brita bgus! | mamah: apa? apa? kmu dpet ranking 1 dikelas? | gue: mah, aku bilang brita bagus, bukan keajaiban -__-"
      "Dengan memakan Make Up, apakah seorang cewek akan cantik dari dalam?"
      "artis itu lucu. mereka bekerja keras agar menjadi terkenal. setelah terkenal, mereka pakai kacamata hitam agar gak dikenal."
      "terkadang gue bodoh kaya patrick, mata duitan kaya mr.krab, bad mood kaya squidward, dan ceria kaya spongebob."
      "Cinta itu tak harus memiliki. Terus apa yang harus gue miliki? GALAU?"
      "#GueSukaSamaLoeTapi gue gak suka sama make up menor yang ada dimuka loe. Plis deh, ITU MUKA, BUKAN BUKU GAMBAAR!!"
      "disekolah, jika kamu cukup lama kekamar mandi, pasti smua orang mengira kamu abis boker. -___-"
    )
  bacotan_num=${#bacotan_array[*]}
  bacotan=${bacotan_array[$((RANDOM%bacotan_num))]}  

  # set tweet_status
  tweet_status="$bacotan"
}
