#!/bin/bash

aksi_array+=("twit_bacot")

# main method
twit_bacot_main() {

  # bacotan, source:
  # http://lintas-terbaru.blogspot.com/2013/11/kata-kata-lucu-update-status-twitter.html
  # http://www.bloggergubug.com/2013/01/update-status-gokil-anti-galau-2013.html
  # http://munafsiq.blogspot.com/2012/09/status-lucu.html
  bacotan_array=(
      "Kalo kamu mau punya pacar yg bisa menjaga kamu & hati kamu... Pacaran aja ama security."
      "Aang: Dulu saya sering masuk angin. Tetapi semenjak kenal dengan klinik Tong Fang, saya jadi pengendali angin. Terimakasih Tong Fang!"
      "Ada 3 alasan orang Insomnia: Jomblo, LDR dan Internet. tapi saya ga yakin sama yg ke 3."
      "KFC, Slamat mlm. mau pesan apa? | Saya mau pesen paket Panas 1 ya | Yakin? gak mau tirai nomor 1? Atau amplop yg ada disaku saya?"
      "Cowok yg suka foto di Toilet mall itu Kecentilannya meningkat 90% "
      "Kalo mau cari pasangan yg Ideal, jangan lupa 4B: Banyak Duit, Berusaha, Berdoa dan Bercerminlah...."
      "Mau apa datang ksni ? | Mau melamar pak.. | Haha.. Kamu jngan melucu yah.. Kerja apa kamu? | Saya pelawak Pak.."
      "*lagi makan diwarteg* *update status* At Pizza Hut with my friends."
      "Hidup itu maju kedepan, bukan mundur kebelakang. Lupakan mantan yang ada dimasa lalu, jadikan ia patokan untuk lebih baik dimasa depan!"
      "PHP itu keahlian yang dibawa sejak lahir. buktinya nggak pernah diajarkan disekolah... tapi udah pada pinter-pinter :|"
      "Kalo dapet pacar itu mudah, Jomblo bakalan punah... lestarikan jomblo..!"
      "Hidup itu jgn dibikin susah, coz dulu org tua kita waktu ngebuat kita itu saat mereka lg seneng2. #bijak"
      "Kematrean seorang wanita, berbanding lurus dengan tingkat kejelekan Prianya. #EaaGitu"
      "Tak ada kata terlambat dalam belajar, ya benar, karena yang terlambat itu biasanya pacar.."
      "#SoSweet itu ketika liat mantan lagi galau ditimeline, karena diselingkuhin pacar barunya."
      "Ummm kamu suka mandi pake formalin yah? Kok nge-Jomblonya awet banget?"
      "Menyalahkan diri sendiri itu ga baik. Daripada nyalahin diri sendiri mendingan nyalahin org lain. #Babijak"
      "Malem Minggu --> Pacaran : Bersandar dibahu pacar | Jomblo : Bersandar dibahu jalan. *Pak Minta Paaak.."
      "Rasa malas bangun pagi selalu bisa dikalahkan oleh rasa mules... "
      "Ga usah sok unyu pake monyong2in bibir gitu dong difoto... Inget Kamu itu bukan tukul ┒(ˇ_ˇ)┎"
      "guru: 3xy + 2y² = a-z. carilah x? | gue: beuh, gampang. itu, ada di antara 3 sama y. pinter kan?"
      "Kentut terbaik adalah kentut dihadapan orang yang kita gak suka. (y)"
      "terkadang gue bodoh kaya patrick, mata duitan kaya mr.krab, bad mood kaya squidward, dan ceria kaya spongebob."
      "Kata cewek 'Semua Lelaki itu brengsek' Nah guys kalo lo brengsek berbanggalah, Brarti lo laki."
      "Jomblo itu sumber dari segala kesepian. Jadi buat dukun yang suka bertapa ditempat sepi, ini bisa dimanfaatkan.."
      "Dalam pacaran Perbedaan Umur itu gak penting, yg penting itu Perbedaan Kelamin.. Inget perbedaaan Kelamin..!!"
      "Kalo ujan gini, pacar pasti jadi pelukable banget ya mblo?"
      "Ternyata air ludah bisa nyembuhin darah rendah.. coba ludahin muka temen lu yang darah rendah, 2 detik langsung naik darahnya.."
      "Pacaran: Tuker-tukeran coklat | LDR: Kirim-kiriman coklat | Jomblo: Tukeran Baygon.."
      "cowok: Neng kita nikah yuk! | cewek: gak ah bang, aku kan masih sekolah | cowok: oh.. kirain libur."
      "Cowok yg suka galau itu kecantikannya naik 90% #Analis"
      "Beb, Semalem aku ngimpi indaaaaah banget | ngimpi kita nikah ya? | bukan, tp ngimpi kita putus | =,,="
      "Anak twitter kalo kehujanan berteduhnya bukan diemperan toko. tapi di timeline.. :|"
      "Punya pacar Cakep itu susah... Susah di jelek-jelekinnya kalo udah putus."
      "Sebenci apa pun cowok sama pelajaran biologi, pasti bakal duduk paling depan kalo lagi ngebahas tentang 'reproduksi' -_-!"
      "jatuh dari sepeda - biasa | jatuh dari motor - lumayan sakit | jatuh dari mobil - BEGO berarti!"
      "Kalau cewek matre lagi sakit mata, mereka nggak perlu ke dokter. Iya.. cukup dikepret pake duit 100 ribuan pasti langsung sembuh :)"
      "cowok sejati itu ngupil pake tangan guru killer!"
      "#KeselAdalah ketika kita lagi download sesuatu, dan ketika udah sampe ████████████ 99%... gagal download!"
      "Abis beli PS baru, PS yg lama langsung rusak. PS yang pengertian.. *Elus-elus PS lama*"
      "Prajurit:'pak, kita telah dikepung dari berbagai arah!' Komandan:'Bagus! sekarang kita bisa menyerang dari segala arah! MUAHAHA!"
      "Jangan suka ngomongin orang dari belakang, kalo kamu ga mau dikentutin."
      "Siapa bilang putus cinta itu sakit hati... Bisa aja kan sakit hati banget ┒(ˇ_ˇ)┎"
      "Sayang, kamu mau gak janji sama aku? | anything for you yank.. | janji ya kalo aku minta putus kamu harus nurut -__-"
      "enak yah pacaran ama Alay. Dia ga mungkin selingkuh, karna bisanya CheL1n6kuH."
      "abis putus. galau. mau mabok. tapi dikulkas cuma ada susu kental manis. apa bisa mabok pake susu kental manis?"
      "Jomblo mah gitu, Ngeliat tukang ojek lagi boncengin penumpangnya aja cemburu #Eh"
      "Lebih baik kejebak macet dijalan, dari pada kejebak kenangan dimasa lalu! :p"
      "Jadi jomblo tu serba salah. Jaga jarak dibilang Sombong. Jaga image dibilang Sok Cool. Jaga komplek dibilang Satpam :|"
      "alien 1: lo percaya manusia gak? | alien 2: itu tahayul!!"
      "Berharap laptop gue berhubungan intim sama HP gue dan berharap mereka akan mempunyai anak iPad."
      "*lagi nonton tv tetangga* *update status* ngantri tiket di XXI panjang beuudh yah ckck."
      "Tabahkan hatimu ,kuatkan imanmu ,putuskan pacarmu, Berikan padaku~"
      "Kebiasaan Jomblo kalo baru OL ditwitter pasti nulis 'Met Pagi' atau sejenisnya biar dpt perhatian. #Uhuk"
      "Pacaran : ngumpulin duit buat nikah | LDR : ngumpulin kangen buat ketemuan | Jomblo : ngumpulin sabun!(۳˚Д˚)۳"
      "artis itu lucu. mereka bekerja keras agar menjadi terkenal. setelah terkenal, mereka pakai kacamata hitam agar gak dikenal."
      "Tuhan jika ia jodohku, dekatkanlah padaku, tp jika ia bukan jodohku, jodohin aku dgn sahabatnya (˘ʃƪ˘)"
      "Cinta itu tak harus memiliki. Terus apa yang harus gue miliki? GALAU?"
      "cowok sejati nempelin upil di baju mantan!kenaapaaa!?'"
      "Percuma nyuruh pacar makan, yang kenyang juga bukan lo ┒(ˇ_ˇ)┎"
      "Mantan itu investasi jangka panjang, kalo kamu kehabisan stok, pergunakanlah mantan #salahbijak"
      "Bt adalah ketika abis mandi gak ada handuk. keluar pake ape gue?"
      "Jomblo kalo tidur ngimpinya apaan sih?"
      "Bang, kecap sebotol berapa? | 20ribu | Mahal amat, di TV aja lebih murah | Yaudah, ibu belinya di TV aja."
      "Buat cewek #Horror itu saat dia tau, kalo cowoknya punya poster anggota boyband gede banget dikamarnya."
      "Anak muda itu baru bangun langsung update status disosmed, bukan mandi..."
      "disekolah, jika kamu cukup lama kekamar mandi, pasti smua orang mengira kamu abis boker. -___-"
      "Lebih nyesek lagi kalo pacaran sama cewek yang lebih tua dari kita. Iya gitu, mau ciuman aja dikira mau nyium emaknya :'"
      "Orang jomblo itu kreatif banget lho. Contoh mereka sengaja pake hape dual sim card, biar bisa sms-sms sendiri, dibales-bales sendiri :p"
      "#Horror itu saat lo beli baju Couple di olshop. Begitu kiriman baju sampe ga taunya lo udah putus.."
      "Anak muda itu bangun tidur langsung nyari HP, ngucapin selamat pagi juga harus disosmed... are u?"
      "Setiap kejahatan akan mendapat balasannya. Cinta bukan kejahatan, makanya jangan heran jika cinta kadang ga dibalas.."
      "Cinta sama org Bodoh itu gpp, tp jgn sampe Dibodoh2in ama org karena Cinta -__-"
      "Emang kalo mau PACARAN harus punya PACAR dulu ya? Terus, kalo kita mau SARAPAN harus jadi SARAP dulu, gitu?"
      "Aa dokter ya? | Kok tau? | Karna Aa udah ngobatin hati neng.. | Masa? Aa kan dokter hewan, Neng.."
      "*KFC* siang mas, brapa orang? | 5 | smoking area atau ga? | Jomblo area ada mbak | ....."
      "Wanita peka pada pikirannya, pria peka pada perasaannya & waria peka terhadap Sirine mobil satpol pp"
      "#GueSukaSamaLoeTapi gue gak suka sama make up menor yang ada dimuka loe. Plis deh, ITU MUKA, BUKAN BUKU GAMBAAR!!"
      "cowok sejati itu main futsal pake bakyak."
      "Siswa relijius itu, waktu UN lembar jawabnya kosong, tapi ninggalin tulisan 'semuanya kuserahkan kepada Tuhan'"
      "Jomblo mah gitu, ngeliat maling dikejar aja langsung cemburu...."
      "gue ini berjiwa penolong, karena itu gue selalu nolongin org2 yang perlu bantuan. Tapi yg cakep aja ┒(ˇ_ˇ)┎"
      "Lihat langit, itulah Ciptaan Tuhan, Lihat Pemandangan, itulah Karya Tuhan, & lihatlah Cermin, itulah Kutukan Tuhan."
      "Jgn pernah ngomongin masa depan, kalo masa lalu ama mantan aja masih ga bisa dilupain ┒(ˇ_ˇ)┎"
      "#SoSweet itu saat lo liat mantan lo lagi jalan sama pacar barunya dan pacarnya lebih jelek dari lo."
      "Dengan memakan Make Up, apakah seorang cewek akan cantik dari dalam?"
      "Hati2 sama yg ngaku Single, mungkin dia Single Parent... #Krik"
      "Lowbat adalah salah satu musuh pacaran dunia maya/LDR yang paling nyata.."
      "Ucapan 'Selamat pagi' di TL adalah salah 1 cara jomblo mencari perhatian, Waspadalah waspadalah."
      "Voldemort: Dlu saya mengidap pnyakit bisul dihidung. tpi smenjak kenal dng klinik TongFang, saya jdi ga pnya hidung..!!"
      "Katanya Gak mau disamain dengan binatang. Tapi masih aja percaya sama ramalan yang lambangnya binatang.."
      "Teman baik waktu minjem barang selalu Dikembalikan tp sahabat waktu minjem barang slalu pura2 lupa dikembalikan.."
      "Jangan salahkan pacar kamu mutusin kamu, salahkan aja diri kamu sendiri kenapa ga mutusin duluan?"
      "Jangan lihat cowok itu dari mobil mewah yang dikendarainya. Lihatlah STNK mobil itu dulu, atas nama dia atau bukan."
      "Hanya karena 'pacar itu dihati, bukan di bio' lantas kamu naruh nama selingkuhan kamu dibio.."
      "Hey kmu, iya kmu!! Kalau pacar kamu cuma pengen paha sama dada kamu doang , suruh dia pacaran sama pegawai KFC! (¬_¬')"
      "co: leh kenalan? | ce: bleh bang | co: nmanya siapa? | ce: sheila | co: bgus bgt, nama panjangnya? | ce: sheilangkangan | co: %!$%!@$%"
      "Kalo cewek bilang, 'semua cowok tuh brengsek!'. Pertanyaannya, Berjenis kelamin apakah Bapa mereka?"
      "Jomblo itu jgn dibully, tapi dipacarin... ckckckckck"
      "#News Diduga ternoda oleh pacar, seorang pemudi nekat mandi dgn deterjen anti noda."
      "Orang pintar, minum tolak angin. Orang jenius, ke Klinik Tong Fang!"
      "orang yg suka nyari perhatian pasti dia bercita-cita jadi pussat Infomarsi. #Eaaa"
      "Anak alim: #AnakMUDAitu keren kalo ibadahnya kuat | Anak alay: #AnakMUDAitu keren kalo lagi joged2 gak jelas di acara musik."
      "pacaran itu penuh gombal, gombal itu bohong, bohong itu dosa, dosa masuk neraka, jadi pacaran itu bikin masuk Neraka"
      "Walau Lo jelek tapi nyari temen itu harus milih2. Ya harus org yang lebih jelek dari lo. Biar lo keliatan cakep #nasehat"
      "Jika mantan adalah masa lalu. Pacar adalah masa depan. Berarti selingkuhan adalah tantangan.."
      "Single: dapet sms dari cewek di diemin | jomblo: dapet sms dari cewek di 'save as draft' buat kenang2an 1x seumur idup."
      "tidur Mblo, kali aja bangun2 langsung punya pacar... #Eaaa"
      "Enak ya jadi alay, Ga pernah sedih. Bisanya cewdih ;("
      "Beb, kalo kamu ga mau aku pacarin,,, gimana kalo kamu aja yg macarin aku? Adil kan?"
      "Satu kebodohan pemain sepak bola adalah selalu mengulangi kesalahan dan kekalahan yang sama pada siaran ulangnya!"
      "gue: mah, ada brita bgus! | mamah: apa? apa? kmu dpet ranking 1 dikelas? | gue: mah, aku bilang brita bagus, bukan keajaiban -__-"
      "Gini nih kalo abis mandi gini,,, cakep gue jadi berlebihan gini... Nasib..."
      "Jadilah mantan yg Elegan, yg ga pernah ngajak balikan tapi sering diajak balikan #Nasehat"
      "Semua LDR itu SETIA - SEring TIdak Apel.... #Eh"
      "Jika cowok kamu ngelirik cewe lain bersyukurlah, Kamu msih diberi cowo normal. Daripada dia ngelirik cowok lain.."
    )
  bacotan_num=${#bacotan_array[*]}
  bacotan=${bacotan_array[$((RANDOM%bacotan_num))]}  

  # set tweet_status
  tweet_status="$bacotan"
}
